name: Cat Facts

on:
  issues:
    types: [opened]

jobs:
  cat_fact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get cat fact
      id: fact
      run: |
        FACT=$(curl -s https://cat-fact.herokuapp.com/facts/random | jq -r '.text')
        echo "::set-output name=fact::$FACT"

    - name: Comment on issue
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fact = `Did you know? Here's a cat fact for you: "${{ steps.fact.outputs.fact }}" 🐱`;
          const comment = context.issue({ body: fact });
          return github.issues.createComment(comment);
